spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: ${USERNAME}
      password: ${PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://127.0.0.1:3307/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: ${USERNAME}
      password: ${PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret:
    key: ${SECRET_KEY}

webclient:
  payment:
    baseurl: ${PAYMENT_WEBCLIENT_BASEURL}
  internal:
    baseurl: ${INTERNAL_WEBCLIENT_BASEURL}

iamport:
  secret: ${IAMPORT_SECRET}
  api:
    key: ${IAMPORT_API_KEY}
